### ISSUE TITLE
[Clarification] Changes in cosine similarities between pairs over time

### ISSUE THREAD

**Issue by santoshbs** [DaBr01/diachronic-word-embeddings-from-german-court-decisions#1]
Thank you, @DaBr01 for making your code available. This is very helpful.

I was wondering whether aligning the models is not necessary for the following:
`comparison.cosine_similarity_over_time("haus", "wohnen", ["1980-1989", "1990-1999"])`

Just wanted to make sure that similarity/distance between a pair of words can be compared across embedding models without having to first align the models.

**Comment by DaBr01** [comment]
Hi @santoshbs, I would say they don't have to be aligned but can be, it depends what we want to show. In the paper, it was used to show a pairwise comparison between three words: In a given year, have the words A and B or A and C been more similar. This can give an indication how well the different models would perform in a classification task. Because the cosine similarity is a relative measure anyway and not dependent on the absolute positions, we don't necessarily have to align the models. If you only want to look at the similarity of two words A and B over time it could make sense to align the models, then you could do something like that:

```
foldernames = ["1980-1989", "1990-1999"]
models = []

for foldername in foldernames:
        models.append(KeyedVectors.load_word2vec_format(foldername + "/" + foldername + ".mod", binary=True))

for model in models[:-1]:
        model = smart_procrustes_align_gensim(models[-1], model)

        a = model.word_vec("haus")
        b = model.word_vec("wohnen")

        cos_sim = dot(a, b) / (norm(a) * norm(b))
```

For the context shift analysis, we always have to align the models because we want to print them in one system of coordinates, i.e. we use the absolute position, rather than just the relative measure of the cosine similarity. Since the absolute position of a word embedding is not really meaningful, we have to align them in order to make them comparable again.

**Comment by santoshbs** [comment]
Thanks a ton, @DaBr01. This is very clear and super helpful.
